name: pakcraftstore
description: PakCraftStore.com
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
#..............Packages..............#
dependencies:
  flutter:
    sdk: flutter
  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  # utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.1.0

  # product specific features
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.7.0

  #..............Packages End..............#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800